#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
##### Bar Appearance #####

sketchybar --bar position=top height=30 blur_radius=50 color=0x00ffffff corner_radius=20 margin=0 y_offset=4

##### Defaults #####

default=(
	padding_left=0
	padding_right=0
	icon.font="Hack Nerd Font:Regular:18.0"
	label.font="SF Pro:Regular:15.0"
	label.color=0xffffffff
	icon.padding_left=4
	icon.padding_right=4
	label.padding_left=4
	label.padding_right=4
)
sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space."$sid" left \
        --subscribe space."$sid" aerospace_workspace_change \
        --set space."$sid" \
        background.color=0x28ffffff \
        background.corner_radius=7 \
        background.height=22 \
        background.width=1 \
        background.drawing=on \
		label.padding_right=13\
		label.padding_left=1\
        label="$sid" \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

sketchybar --set left_items \
	background.color="$DARK_BAR_COLOR_60" \
	background.corner_radius=50 \
	background.height=36 \
	background.padding_left=30 \
	background.padding_right=30 \
	background.margin=20

##### Adding Right Items #####
sketchybar --add item calendar right \
	--set calendar icon="" \
	label.font="SF Pro:Regular:14.0" \
	update_freq=50 \
	click_script="open -a Calendar" \
	script="$PLUGIN_DIR/clock.sh"

# Battery
sketchybar --add item battery right

sketchybar --set battery \
	update_freq=120 \
	script="$PLUGIN_DIR/battery.sh" \
	label.font="SF Pro:Regular:14.0"

sketchybar --subscribe battery system_woke power_source_change

Spotify currently playing label
 sketchybar --add item spotify right
 sketchybar --set spotify \
 	script="$HOME/.config/sketchybar/items/spotify.sh" \
 	icon.font="Hack Nerd Font:Bold:18.0" \
	icon= \
 	label.font="SF Pro:Regular:14.0" \
 	update_freq=4 \
 	background.padding_right=2

 sketchybar --add bracket right_items spotify volume battery calendar

sketchybar --set right_items \
	background.color="$DARK_BAR_COLOR_60" \
	background.corner_radius=50 \
	background.height=36 \
	background.padding_left=30 \
	background.padding_right=30

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
